name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: url-shortener
  EKS_CLUSTER: url-shortener-cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::809554585891:role/GitHubActions-UrlShortener-OIDC
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity
